# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47fc0baaa51b9a7f7a5a4177365808dd6617b1bb2bc8508b5184261f6f552067271b42c039d1841bf2acb2d4e725291a071d7fa2cab9db704155dac83b3c8bb4

test:
  secret_key_base: 03e914cdf16ff703f7fb466ad7cbba86fd84ebdc8249b2ab12ce5c8b04cbe312116f64591dd0a5980ccfa8d2e19aa4df6c0469f42d4287dd8ef145b1faca6016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
